export const LOGIN_USER = 'Login_User';
export const USER_DETAILS = 'User_Details'
export const CREATE_TUTOR = 'Create_Tutor'
export const CREATE_STUDENT = 'Create_Student'
export const GET_TUTORS_LIST ='Get_Tutors_List'
export const GET_STUDENTS_LIST ='Get_Students_List'
export const TOAST_MANAGER = 'Toast_Manager'
export const SUBJECT_MODEL = 'Subject_Model'
export const GET_AVAILABLE_SLOTS = 'Get_Available_Slots'
export const BOOK_SLOTS = 'Book_Slots'
export const SELECTED_STUDENT = 'Selcted_Slot'
export const GET_BOOKED_SLOTS = 'Get_Booked_Slots'
//export const API_URL = 'https://preyosacademy-userservice.onrender.com';
export const API_URL = 'http://localhost:4000';
export const jwtSecretCode = 'preyosaccademy';
export const RESET_STORE = "RESET_STORE";
